version: '3.8'
services:
  jms:
    image: vromero/activemq-artemis
    ports:
      - 88161:8161
      - 61616:61616
    restart: always
    networks:
      - guru
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - guru 
  eureka:
    image: sfgbeerworks/mssc-brewery-eureka
    ports:
      - "8761:8761"
    restart: always
    networks:
      - guru  
  config:
    image: sfgbeerworks/mssc-config-server
    ports:
      - "8888:8888" 
    restart: always
    networks:
      - guru 
  gateway:
    image: sfgbeerworks/mssc-brewery-gateway
    ports:
      - "9090:9090"
    depends_on:
       - eureka
       - inventory-service   
    restart: always
    networks:
      - guru       
  inventory-service:
    image: sfgbeerworks/mssc-beer-inventory-service
    ports:
      - "8082:8082"
    depends_on:
       - eureka
       - jms   
    restart: always
    networks:
      - guru   
  mssc-beer-service:
    image: sfgbeerworks/mssc-beer-service
    ports:
      - "8082:8082"
    depends_on:
       - eureka
       - jms   
    restart: always
    networks:
      - guru 
  mssc-beer-order-service:
    image: sfgbeerworks/mssc-beer-order-service
    ports:
      - "8082:8082"
    depends_on:
       - eureka
       - jms   
    restart: always
    networks:
      - guru                                           
networks:
  guru: